export const data = {
  id: 14,
  idLoaiHinhVanChuyen: 4,
  objLoaiHinhVanChuyen: {
    id: 4,
    tenVietTat: "DD",
    tenLoaiHinh: "Door - Door",
    deleted: true,
  },
  idKhachHang: 1,
  objKhachHang: {
    id: 1,
    maKhachHang: "CTY.31234123412412",
    tenKhachHang: "Khách Hàng 1",
    tenVietTat: "KH1",
    loaiKhachHang: "CTY",
    address: null,
    phoneNumber: null,
    email: null,
    cmt: "31234123412412",
    soDuDauKy: null,
    idPhuongPhapThanhToan: null,
    hanMuc: null,
    startDatePay: 25,
    endDatePay: 29,
    deleted: true,
    createDate: "2023-06-22T14:43:14.877Z",
    updateDate: null,
  },
  idNhaXe: 2,
  objNhaXe: {
    id: 2,
    maKhachHang: "CTY.234141241",
    tenKhachHang: "Khách Hàng 2",
    tenVietTat: "KH2",
    loaiKhachHang: "CTY",
    address: "",
    phoneNumber: "",
    email: "dung.ckay1234@gmail.com",
    cmt: "234141241",
    soDuDauKy: null,
    idPhuongPhapThanhToan: null,
    hanMuc: null,
    startDatePay: 1,
    endDatePay: 23,
    deleted: true,
    createDate: "2023-06-22T14:43:37.557Z",
    updateDate: "2023-11-05T10:19:17.807Z",
  },
  idXeCongTy: null,
  objXeCongTy: null,
  idNVCSKH: null,
  objNVCSKH: null,
  idNVKH: null,
  objNVKH: null,
  idSALE: 1,
  objSALE: {
    id: 1,
    idLoaiNhanVien: 1,
    tenNhanVien: "admin",
    maNhanVien: "admin",
    phoneNumber: "",
    birthday: null,
    gender: null,
    address: null,
    username: "TESTER",
    password: "123456",
  },
  codeOrder: "DD.29062023.1",
  noVo: 1,
  idLoaiVo: null,
  objLoaiVo: null,
  trongLuong: "",
  idHangTau: null,
  objHangTau: "",
  ngayDong: "2023-06-29T00:00:00.000Z",
  gioDong: "00:00",
  noiDong: "",
  ngayTra: "2023-06-29T00:00:00.000Z",
  gioTra: "00:00",
  noiTra: "",
  noCont: "",
  noSeal: "",
  licensePlates: "",
  nameDriver: "",
  phoneNumberDriver: "",
  noteNLH: "",
  diaDiemTra: "",
  diaDiemDong: "",
  nguoiTraHang: "",
  nguoiLayHang: "",
  phoneNumberNLH: "",
  phoneNumberNTH: "",
  noteNTH: "",
  noteOrder: "",
  status: "CREATE",
  pheDuyet: "ĐÃ DUYỆT",
  reasonCancel: "",
  created_Date: "2023-06-29T09:35:46.907Z",
  updated_Date: "2023-06-29T09:36:38.690Z",
  hanThu: "25/11",
  hanTra: "29/11",
  ngayTraPhoi: "",
  ngayNhanPhoi: "",
  tongTienThu: 13000000,
  tongTienChi: 12500000,
  payNote: null,
  payDay: null,
  revenueNote: null,
  revenueDay: null,
  chiPhiPhatSinhThuArr: [
    {
      id: 23,
      chiphiphatsinhthu: 3000000,
      isChiPhiKhac: false,
      isKhachHang: true,
      isTraHo: false,
      isCaXe: false,
      isTLTK: false,
      isLachHuyen: false,
      isNang: false,
      isHa: false,
      isCSHT: false,
      isPhiRu: false,
      isPayment: false,
      tenchiphithu: "cước thu",
      note: null,
      soChungTu: null,
    },
    {
      id: 24,
      chiphiphatsinhthu: 10000000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: true,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "trả hộ",
      note: null,
      soChungTu: null,
    },
    {
      id: 25,
      chiphiphatsinhthu: 1000000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "Khác",
      note: null,
      soChungTu: null,
    },
    {
      id: 26,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 27,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: true,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 28,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: true,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 29,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: true,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 30,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: true,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 31,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: true,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 32,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: true,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 33,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: false,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: true,
      isCSHT: null,
      isPhiRu: true,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
    {
      id: 32,
      chiphiphatsinhthu: 100000,
      isChiPhiKhac: true,
      isKhachHang: false,
      isTraHo: null,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: true,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphithu: "test",
      note: null,
      soChungTu: null,
    },
  ],
  chiPhiPhatSinhChiArr: [
    {
      id: 14,
      chiphiphatsinhchi: 12000000,
      isBenThuBa: false,
      isChiPhiKhac: false,
      isCom: false,
      isNhaXe: true,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphichi: "cước chi",
      note: null,
      soChungTu: null,
    },
    {
      id: 15,
      chiphiphatsinhchi: 500000,
      isBenThuBa: false,
      isChiPhiKhac: false,
      isCom: true,
      isNhaXe: false,
      isCaXe: null,
      isTLTK: null,
      isLachHuyen: null,
      isNang: null,
      isHa: null,
      isCSHT: null,
      isPhiRu: null,
      isPayment: false,
      tenchiphichi: "com",
      note: null,
      soChungTu: null,
    },
  ],
  chiPhiXeCongTyArr: [],
  giaDau: 0,
  soDauTieuThu: 0,
  dauCapBoSung: 0,
  luongChuyen: 0,
  congTacPhi: 0,
  chiPhiKhac1: 0,
  chiPhiKhac2: 0,
  chiPhiKhac3: 0,
  chiPhiKhac4: 0,
  com1: 0,
  com2: 0,
  com3: 0,
  com4: 0,
  chiPhiCongTy1: 0,
  chiPhiCongTy2: 0,
};

export const thuItemList = [
  { id: 1, label: "Cước thu", dataKey: "isKhachHang" },
  { id: 2, label: "Ca xe", dataKey: "isCaXe" },
  { id: 3, label: "TL TK", dataKey: "isTLTK" },
  { id: 4, label: "Lạch huyện", dataKey: "isLachHuyen" },
  { id: 5, label: "CSHT", dataKey: "isCSHT" },
  { id: 6, label: "Nâng", dataKey: "isNang" },
  { id: 7, label: "Hạ", dataKey: "isHa" },
  { id: 8, label: "Phí ru", dataKey: "isPhiRu" },
  { id: 9, label: "Chi phí khác", dataKey: "isChiPhiKhac" },
];

export const chiItemList = [
  { id: 1, label: "Cước chi", dataKey: "isnhaxe" },
  { id: 2, label: "Ca xe", dataKey: "isCaXe" },
  { id: 3, label: "TL TK", dataKey: "isTLTK" },
  { id: 4, label: "Lạch huyện", dataKey: "isLachHuyen" },
  { id: 5, label: "CSHT", dataKey: "isCSHT" },
  { id: 6, label: "Nâng", dataKey: "isNang" },
  { id: 7, label: "Hạ", dataKey: "isHa" },
  { id: 8, label: "Phí ru", dataKey: "isPhiRu" },
  { id: 9, label: "Chi phí khác", dataKey: "isChiPhiKhac" },
  { id: 10, label: "Cơm", dataKey: "isCom" },
];
